# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Hello. I'm Nur E Alam Khan."
email: "porosh80@gmail.com"
description: "I'm a software developer and project manager from Dhaka creating useful things for the web & mobile."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://porosh.github.io" # the base hostname & protocol for your site, e.g. https://example.com
github_username: "porosh"
linkedin_username: "nurealamkhan"
online_cv_link: "https://docs.google.com/document/d/1jpi6vE4eYIdbZocTXxP7ZpdmA3W4lDWWQ0VsCYgCYfk"
formspree_form_endpoint: "https://formspree.io/f/xdkadada"

# SEO Settings
keywords: "Software Engineer, Project Manager, Web Developer, Mobile Developer, Cloud Computing, React Native, Python, PHP, AI, Machine Learning, Get Freelance Job, Hire React Native Developer, Remote Software Engineer, Full-Stack Developer, Mobile App Developer for Hire, Backend Developer, Cloud Architect, AI Engineer, Machine Learning Specialist, IT Consultant, DevOps Engineer, SaaS Development, Agile Project Manager, API Developer, Cross-Platform Developer, AWS & Azure Expert, Startup Tech Consultant"
author: "Nur E Alam Khan"
robots: "index, follow"
meta_image: "/porosh.github.io.jpg"
twitter_username: "porosh80"

# Open Graph (Facebook, LinkedIn) SEO
og:
  title: "Hello. I'm Nur E Alam Khan."
  description: "Experienced Software Engineer and Project Manager specializing in mobile & web development, cloud computing, and AI."
  type: "website"
  url: "https://porosh.github.io"
  image: "/porosh.github.io.jpg"
  site_name: "Nur E Alam Khan Portfolio"

# Twitter SEO
twitter:
  card: "summary_large_image"
  title: "Hello. I'm Nur E Alam Khan."
  description: "Experienced Software Engineer and Project Manager specializing in mobile & web development, cloud computing, and AI."
  image: "//porosh.github.io.jpg"
  site: "@porosh80"

# Build settings
markdown: kramdown
# theme: phantom # Uncomment once published to RubyGems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
paginate: 10
paginate_path: "/page:num/"

pagination:
  enabled: true
  debug: false
  collection: "posts"
  per_page: 10
  permalink: "/page/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  category: "posts"
  tag: ""
  locale: ""
  trail:
    before: 2
    after: 2
  extension: html
  indexpage: "index"

############################################################

### Phantom settings
footer_text: "© 2025 Nur E Alam Khan"
admin_name: "Nur E Alam Khan"
google_analytics: "UA-9999999-99" # Update with your own tracking ID
enable_contact: false

#### Phantom Navigation menu
enable_nav: true
nav_item:
  - { url: "/", text: "Home" }
  - { url: "/skills", text: "My Skills" }
  - { url: "/about", text: "About" }
  - {
      url: "https://docs.google.com/document/d/1jpi6vE4eYIdbZocTXxP7ZpdmA3W4lDWWQ0VsCYgCYfk",
      text: "My CV",
    }
  - {
      url: "https://calendar.app.google/pRqhHFDRW3TdUZiz6",
      text: "Book An Appointment",
    }
  - { url: "/contact", text: "Contact Me" }
